### ISSUE TITLE
Canceling sync process

### ISSUE THREAD

**Issue by orschiro** [faisalraja/flickrsmartsync#19]
Hi there, 

Am I correct that there is no way to cancel the sync process?

I tried `CTRL` `C` as well as `D` but they do not successfully abort the process.

**Comment by orschiro** [comment]
@faisalraja 

You won't implement a canceling feature?

**Comment by faisalraja** [comment]
I thought it was in the thomascobb changes. I'll double check if not.

**Comment by thomascobb** [comment]
No, it wasn't in my changes

**Comment by paedrae** [comment]
Great work, but the "delete" remote is a must-have: if I need to stop the sync and then restart I find many duplicated images on Flickr. 64GB of image library to upload with a 256Kbps upload limit :( does not permit to have a all-time-running upload task (my wife will kill me if she can'r read mail and other stuff...)

Another one: in #22 thomascobb discuss about a sync-from local|remote|all : if I'm right only the all is implemented.

**Comment by pejobo** [comment]
Hitting "crtl-c" does the trick for me (linux).

**Comment by gnuton** [comment]
The main problem of using CTRL-C or DELETE is the fact that it stops the current transfer. So if you are downloading images the tranfer will be suddenly interrupted and you will get a corrupted image.
I fixed that in my branch but the code is slighlty different from the  one here, since I'm using concurrent threads to download and upload stuff to flickr in parallel.
The duplicated images that paedrae was talking about I believe comes from another bug.. but I have to investigate more on that.
