### ISSUE TITLE
Remove windows drive letter from ablum/set name?

### ISSUE THREAD

**Issue by jmrichardson** [faisalraja/flickrsmartsync#27]
Hello,

I just got your python program working on win7 using python27.  My directory layout looks something like this:

G:\My Pictures\2001
G:\My Pictures\2001\January
G:\My Pictures\2001\January\photo1.jpg
...

The uploaded set on flickr contains the "G:\" in the album name.  My concern is if I move the "My Pictures" folder to another drive letter, it won't recognize that they have already been uploaded.  Can you update the code to strip the drive letter?

Thanks in advance,
John

**Comment by questking** [comment]
@faisalraja did you fix this issue?

**Comment by faisalraja** [comment]
I don't remember. But maybe. If not let me know.

**Comment by questking** [comment]
its still there. it uses the whole dir path as title. Then i tried the custom set but it required me to give confirmation on the title. This worked fine. But since i want to automate this script, that confirmation will have to be answered. That's why I removed the confirmation dialog from the script. As it shows me the title it has chosen, once I am satisfied with the result, that confirmation dialog will hinder the process. Maybe there should be a code that takes a final confirmation and doesn't show the dialog again. 
Kudos.

PS: I am a new to coding.

**Comment by pejobo** [comment]
This should be fixed in master with 2b9aa2fb5bd1c50f21f414299944781e3e4acbda
